name: unpaid-labor-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - statsmodels>=0.12.0
  - jupyter>=1.0.0
  - pytest>=6.0.0
  - pytest-cov>=2.10.0
  - tqdm>=4.60.0
  - openpyxl>=3.0.7
  - xlsxwriter>=1.4.0
  - numba>=0.53.0
  - pip
  - pip:
    - black>=21.0.0
    - flake8>=3.9.0
